# For deployment to github pages, check resource https://docs.travis-ci.com/user/deployment/pages/
# In GitHub settings, go to GitHub Pages section, Source subsection, and select "gh-pages branch" from dropdown.  That option WON'T APPEAR if you don't have a branch called 'gh-pages'.
sudo: required
language: python # python will be pre-installed on server thanks to this
python:
- "2.7"
before_install:
- pwd
- DIR_BASE=$(pwd)
- mkdir temp-install-sage
- cd temp-install-sage
- pwd
- wget http://mirrors.mit.edu/sage/linux/64bit/sage-8.2-Ubuntu_16.04-x86_64.tar.bz2
- ls
- tar -xf sage-8.2-Ubuntu_16.04-x86_64.tar.bz2
- ls
- ln -s "${DIR_BASE}"/temp-install-sage/SageMath/sage /usr/local/bin/sage
- which sage
- sage --version
script:
- uname -a
- pwd
- cd docs
- pwd
- make html
- # move html files into place
- mv build/html/* .
- # include .nojekyll (see https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/)
- touch .nojekyll
- ls -a
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # You need to create this key (public access token) following the steps in https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/.  Make sure the PAT has the appropriate repo or public_repo access (or both).  Then copy and paste this PAT as an environment variable "GITHUB_API_KEY" in Travis settings for the appropriate repository.
  local_dir: docs
  on:
    branch: master
