sudo: required
language: python # Python will be pre-installed on server thanks to this
python:
- "2.7"
script:
- pwd
- cd doc
- pwd
- make html
- # move html files into place if necessary
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # see settings in Travis
  local_dir: doc/build/html
  on:
    branch: master

