sudo: required
language: python # Python2 will be pre-installed on server thanks to this
before_install:
- pip install sphinx
script:
- # comment out sage.all
- make html
- # move html files into place if necessary
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # see settings in Travis
  local_dir: doc/build/html
  on:
    branch: master

